AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Buschi (2020) — AWS Batch overflow processing.
  Used for overflow when primary EC2 nodes are at capacity.
  Scales from zero; c5.2xlarge for CPU-heavy and m5.4xlarge for memory-heavy jobs.

Parameters:
  BatchServiceRoleArn:
    Type: String
    Description: ARN of the IAM role for AWS Batch service (AWSBatchServiceRole)
  EcsInstanceRoleArn:
    Type: String
    Description: ARN of the IAM instance profile for ECS container instances
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for the Batch compute environment
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for the Batch compute environment

Resources:
  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Buschi AWS Batch compute environment
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: buschi-batch-sg
        - Key: Project
          Value: buschi

  # Managed compute environment — scales from 0 to 64 vCPUs
  BuschiComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: buschi-print-overflow
      Type: MANAGED
      State: ENABLED
      ServiceRole: !Ref BatchServiceRoleArn
      ComputeResources:
        Type: EC2
        MinvCpus: 0
        MaxvCpus: 64
        DesiredvCpus: 0
        InstanceTypes:
          - c5.2xlarge   # CPU-heavy jobs (8 vCPU, 16 GB)
          - m5.4xlarge   # Memory-heavy jobs (16 vCPU, 64 GB)
        InstanceRole: !Ref EcsInstanceRoleArn
        Subnets: !Ref SubnetIds
        SecurityGroupIds:
          - !Ref BatchSecurityGroup
        Tags:
          Project: buschi

  BuschiJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: buschi-print-overflow-queue
      State: ENABLED
      Priority: 1
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref BuschiComputeEnvironment

  # Job definition: 8 vCPUs, 32 GB, 2 retries, 10 min timeout
  BuschiJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: buschi-print-job
      Type: container
      ContainerProperties:
        Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/buschi-print:latest"
        Vcpus: 8
        Memory: 32768
        JobRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/buschi-batch-job-role"
      RetryStrategy:
        Attempts: 2
      Timeout:
        AttemptDurationSeconds: 600   # 10 min max per job

Outputs:
  ComputeEnvironmentArn:
    Description: Buschi AWS Batch compute environment ARN
    Value: !Ref BuschiComputeEnvironment

  JobQueueArn:
    Description: Buschi AWS Batch job queue ARN
    Value: !Ref BuschiJobQueue

  JobDefinitionArn:
    Description: Buschi AWS Batch job definition ARN
    Value: !Ref BuschiJobDefinition
