AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Buschi (2020) — S3 + SQS Job Pipeline.
  Hybrid on-premise/cloud job flow: client uploads PDF to S3, S3 event triggers
  SQS, EC2 node processes job, output pushed to S3 for on-premise print server.

Resources:
  # Incoming jobs bucket
  IncomingJobsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "buschi-print-jobs-incoming-${AWS::AccountId}"
      LifecycleConfiguration:
        Rules:
          - Id: transition-to-ia
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
            ExpirationInDays: 365
      NotificationConfiguration:
        QueueConfigurations:
          - Event: "s3:ObjectCreated:*"
            Queue: !GetAtt PrintJobQueue.Arn
      Tags:
        - Key: Project
          Value: buschi

  # Output bucket for processed jobs
  OutputJobsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "buschi-print-jobs-output-${AWS::AccountId}"
      Tags:
        - Key: Project
          Value: buschi

  # Dead-letter queue — jobs that fail 3 times go here for manual review
  PrintJobDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: buschi-print-job-dlq
      MessageRetentionPeriod: 1209600   # 14 days
      Tags:
        - Key: Project
          Value: buschi

  # Main job queue
  PrintJobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: buschi-print-job-queue
      VisibilityTimeout: 300   # 5 min — max single-job processing time
      MessageRetentionPeriod: 1209600   # 14 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt PrintJobDLQ.Arn
        maxReceiveCount: 3   # 3 failures -> DLQ for manual review
      Tags:
        - Key: Project
          Value: buschi

  # Allow S3 to publish to SQS
  PrintJobQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref PrintJobQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt PrintJobQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::buschi-print-jobs-incoming-${AWS::AccountId}"

Outputs:
  IncomingBucketName:
    Description: S3 bucket for incoming print jobs
    Value: !Ref IncomingJobsBucket

  OutputBucketName:
    Description: S3 bucket for processed print output
    Value: !Ref OutputJobsBucket

  PrintJobQueueUrl:
    Description: SQS queue URL for print jobs
    Value: !Ref PrintJobQueue

  PrintJobQueueArn:
    Description: SQS queue ARN for print jobs
    Value: !GetAtt PrintJobQueue.Arn
    Export:
      Name: !Sub "${AWS::StackName}-PrintJobQueueArn"

  PrintJobDLQUrl:
    Description: Dead-letter queue URL for failed jobs
    Value: !Ref PrintJobDLQ
