AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Buschi (2020) — Vertical Scaling RDS Strategy.
  Provisions an RDS PostgreSQL instance with provisioned IOPS storage
  for print job metadata. Aurora Serverless v2 was not available in 2020;
  vertical scaling with io1 was the standard approach.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for the RDS instance
  DbSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for the DB subnet group (minimum 2 AZs)
  BuschiSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group of the Buschi processing nodes (source for DB access)
  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Master password for the RDS instance

Resources:
  BuschiDbSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Buschi RDS subnet group
      SubnetIds: !Ref DbSubnetIds
      Tags:
        - Key: Project
          Value: buschi

  BuschiDbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Buschi RDS - allow access from processing nodes
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupId: !Ref BuschiSecurityGroupId
      Tags:
        - Key: Name
          Value: buschi-rds-sg
        - Key: Project
          Value: buschi

  # Initial: db.m4.large (2 vCPU, 8 GB RAM)
  # Scaling path: db.m4.4xlarge (16 vCPU, 64 GB RAM)
  # Triggers: FreeableMemory < 2GB | CPUUtilization > 70% | DatabaseConnections > 80% of max
  BuschiDatabase:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBInstanceIdentifier: buschi-print-metadata
      DBInstanceClass: db.m4.large
      Engine: postgres
      EngineVersion: "14.10"
      MasterUsername: buschi_admin
      MasterUserPassword: !Ref DBPassword
      AllocatedStorage: "500"
      StorageType: io1
      Iops: 3000
      MultiAZ: false
      DBSubnetGroupName: !Ref BuschiDbSubnetGroup
      VPCSecurityGroups:
        - !Ref BuschiDbSecurityGroup
      BackupRetentionPeriod: 7
      PreferredBackupWindow: "03:00-04:00"
      PreferredMaintenanceWindow: "sun:04:00-sun:05:00"
      MonitoringInterval: 60
      EnablePerformanceInsights: true
      Tags:
        - Key: Name
          Value: buschi-print-metadata
        - Key: Project
          Value: buschi
        - Key: ScaleType
          Value: vertical
        - Key: UpgradeTo
          Value: db.m4.4xlarge

Outputs:
  DBInstanceIdentifier:
    Description: RDS instance identifier
    Value: !Ref BuschiDatabase

  DBEndpoint:
    Description: RDS endpoint address
    Value: !GetAtt BuschiDatabase.Endpoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-DBEndpoint"

  DBPort:
    Description: RDS endpoint port
    Value: !GetAtt BuschiDatabase.Endpoint.Port
