AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Vertical Scaling Recipe — S3 + SQS Job Pipeline.
  Hybrid on-premise/cloud job flow: client uploads file to S3, S3 event triggers
  SQS, EC2 node processes job, output pushed to S3 for downstream consumption.
  Use when workload is batch/queue-driven and a single node processes jobs sequentially.

Resources:
  # Incoming jobs bucket
  IncomingJobsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "vertical-scaling-jobs-incoming-${AWS::AccountId}"
      LifecycleConfiguration:
        Rules:
          - Id: transition-to-ia
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
            ExpirationInDays: 365
      NotificationConfiguration:
        QueueConfigurations:
          - Event: "s3:ObjectCreated:*"
            Queue: !GetAtt JobQueue.Arn
      Tags:
        - Key: ScalingPattern
          Value: vertical

  # Output bucket for processed jobs
  OutputJobsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "vertical-scaling-jobs-output-${AWS::AccountId}"
      Tags:
        - Key: ScalingPattern
          Value: vertical

  # Dead-letter queue — jobs that fail 3 times go here for manual review
  JobDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: vertical-scaling-job-dlq
      MessageRetentionPeriod: 1209600   # 14 days
      Tags:
        - Key: ScalingPattern
          Value: vertical

  # Main job queue
  JobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: vertical-scaling-job-queue
      VisibilityTimeout: 300   # 5 min — max single-job processing time
      MessageRetentionPeriod: 1209600   # 14 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt JobDLQ.Arn
        maxReceiveCount: 3   # 3 failures -> DLQ for manual review
      Tags:
        - Key: ScalingPattern
          Value: vertical

  # Allow S3 to publish to SQS
  JobQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref JobQueue
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt JobQueue.Arn
            Condition:
              ArnLike:
                aws:SourceArn: !Sub "arn:aws:s3:::vertical-scaling-jobs-incoming-${AWS::AccountId}"

Outputs:
  IncomingBucketName:
    Description: S3 bucket for incoming jobs
    Value: !Ref IncomingJobsBucket

  OutputBucketName:
    Description: S3 bucket for processed output
    Value: !Ref OutputJobsBucket

  JobQueueUrl:
    Description: SQS queue URL for jobs
    Value: !Ref JobQueue

  JobQueueArn:
    Description: SQS queue ARN for jobs
    Value: !GetAtt JobQueue.Arn
    Export:
      Name: !Sub "${AWS::StackName}-JobQueueArn"

  JobDLQUrl:
    Description: Dead-letter queue URL for failed jobs
    Value: !Ref JobDLQ
