AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Vertical Scaling Recipe — CloudWatch Monitoring.
  Alarms that signal when to scale up the primary EC2 instance or RDS instance.
  These alarms are decision triggers for operators, not automatic scaling actions.
  Vertical scaling requires a human decision: stop instance, resize, restart.

Parameters:
  OpsTeamEmail:
    Type: String
    Description: Email address for ops team SNS notifications
  Ec2InstanceId:
    Type: String
    Description: EC2 instance ID to monitor (primary compute node)
  DbInstanceIdentifier:
    Type: String
    Description: RDS instance identifier (e.g., vertical-scaling-db)
  ProvisionedReadIops:
    Type: Number
    Default: 3000
    Description: Provisioned read IOPS on the RDS instance (alarm threshold = 90% of this value)

Resources:
  OpsTeamTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: vertical-scaling-ops-alerts
      Subscription:
        - Protocol: email
          Endpoint: !Ref OpsTeamEmail

  # EC2 CPU high — operator signal to evaluate next instance size
  # Action: stop instance → change instance type → start instance
  Ec2CpuHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: vertical-scaling-ec2-cpu-high
      AlarmDescription: >
        EC2 CPU > 80% for 5 min — evaluate upgrade to next instance size.
        Vertical scaling action: stop instance, modify InstanceType, start instance.
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Dimensions:
        - Name: InstanceId
          Value: !Ref Ec2InstanceId
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref OpsTeamTopic

  # RDS IOPS saturation — signal to increase provisioned IOPS or upgrade instance
  # Action: modify RDS instance (Iops increase, or DBInstanceClass upgrade)
  RdsIopsSaturationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: vertical-scaling-rds-iops-saturation
      AlarmDescription: >
        RDS ReadIOPS > 90% of provisioned — increase provisioned IOPS or upgrade instance class.
        Vertical scaling action: modify DB instance IOPS or instance class (causes brief outage).
      MetricName: ReadIOPS
      Namespace: AWS/RDS
      Dimensions:
        - Name: DBInstanceIdentifier
          Value: !Ref DbInstanceIdentifier
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: !Sub "${ProvisionedReadIops}"
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref OpsTeamTopic

  # SQS queue depth — jobs backing up faster than they are processed
  # Action: check if EC2 instance is at CPU/memory limit; if so, scale up instance
  SqsQueueDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: vertical-scaling-sqs-queue-depth
      AlarmDescription: >
        SQS visible messages > 100 — processing cannot keep pace with incoming jobs.
        Check EC2 CPU/memory utilization; if saturated, upgrade instance type.
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Dimensions:
        - Name: QueueName
          Value: vertical-scaling-job-queue
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref OpsTeamTopic

  # SQS oldest message — job stuck or processing failure
  # Action: investigate EC2 process health; restart service if needed
  SqsOldestMessageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: vertical-scaling-sqs-oldest-message
      AlarmDescription: >
        SQS oldest message > 30 min — jobs stuck, possible processing failure.
        Check EC2 application logs; service may need restart or instance may be unresponsive.
      MetricName: ApproximateAgeOfOldestMessage
      Namespace: AWS/SQS
      Dimensions:
        - Name: QueueName
          Value: vertical-scaling-job-queue
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1800
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref OpsTeamTopic

Outputs:
  OpsTeamTopicArn:
    Description: SNS topic ARN for ops team alerts
    Value: !Ref OpsTeamTopic
