AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Vertical Scaling Recipe - AWS Batch Overflow Processing.
  Provides elastic overflow capacity when the primary vertical-scaled EC2 nodes
  are saturated. Scales from zero; Batch handles bursts without permanently
  resizing the primary instance.
  Prerequisite: build your processing container image and push to ECR before deploying.
  ECR image expected at: <account>.dkr.ecr.<region>.amazonaws.com/vertical-scaling-processor:latest

Parameters:
  BatchServiceRoleArn:
    Type: String
    Description: ARN of the IAM role for AWS Batch service (AWSBatchServiceRole)
  EcsInstanceRoleArn:
    Type: String
    Description: ARN of the IAM instance profile for ECS container instances (ecsInstanceRole)
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for the Batch compute environment
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnets for the Batch compute environment

Resources:
  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Vertical scaling recipe - AWS Batch compute environment
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: vertical-scaling-batch-sg
        - Key: ScalingPattern
          Value: vertical

  # Managed compute environment - scales from 0 to 64 vCPUs
  # MinvCpus: 0 means no idle cost; instances terminate when queue drains.
  # Adapt MaxvCpus to match your overflow budget.
  OverflowComputeEnvironment:
    Type: AWS::Batch::ComputeEnvironment
    Properties:
      ComputeEnvironmentName: vertical-scaling-overflow
      Type: MANAGED
      State: ENABLED
      ServiceRole: !Ref BatchServiceRoleArn
      ComputeResources:
        Type: EC2
        MinvCpus: 0
        MaxvCpus: 64
        DesiredvCpus: 0
        InstanceTypes:
          - c5.2xlarge   # CPU-heavy jobs (8 vCPU, 16 GB)
          - m5.4xlarge   # Memory-heavy jobs (16 vCPU, 64 GB)
        InstanceRole: !Ref EcsInstanceRoleArn
        Subnets: !Ref SubnetIds
        SecurityGroupIds:
          - !Ref BatchSecurityGroup
        Tags:
          ScalingPattern: vertical

  OverflowJobQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      JobQueueName: vertical-scaling-overflow-queue
      State: ENABLED
      Priority: 1
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref OverflowComputeEnvironment

  # Job definition: 8 vCPUs, 32 GB RAM, 2 retries, 10 min timeout
  # Replace the ECR image URI with your actual processing container.
  OverflowJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      JobDefinitionName: vertical-scaling-processor-job
      Type: container
      ContainerProperties:
        Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/vertical-scaling-processor:latest"
        Vcpus: 8
        Memory: 32768
        JobRoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/vertical-scaling-batch-job-role"
      RetryStrategy:
        Attempts: 2
      Timeout:
        AttemptDurationSeconds: 600   # 10 min max per job

Outputs:
  ComputeEnvironmentArn:
    Description: AWS Batch overflow compute environment ARN
    Value: !Ref OverflowComputeEnvironment

  JobQueueArn:
    Description: AWS Batch overflow job queue ARN
    Value: !Ref OverflowJobQueue

  JobDefinitionArn:
    Description: AWS Batch job definition ARN
    Value: !Ref OverflowJobDefinition
