AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Horizontal Scaling Recipe — CloudFront CDN.
  Offloads static assets (images, JS, CSS) from ALB origin.
  Reduces ALB and ASG origin load by ~60-70% during peak traffic.
  WAF web ACL for DDoS protection and rate limiting at the edge.
  Note: WAF web ACL must be created in us-east-1 (CloudFront is a global service).

Parameters:
  AlbDnsName:
    Type: String
    Description: DNS name of the ALB (from horizontal-alb-config stack)
  WafWebAclArn:
    Type: String
    Description: WAF web ACL ARN (must be in us-east-1 for CloudFront)

Resources:
  # S3 bucket for static assets served from CloudFront edge locations
  StaticAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "horizontal-scaling-static-${AWS::AccountId}"
      Tags:
        - Key: ScalingPattern
          Value: horizontal

  StaticAssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticAssetsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub "arn:aws:s3:::horizontal-scaling-static-${AWS::AccountId}/*"

  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Horizontal scaling recipe — static assets OAI

  AppDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: Horizontal scaling recipe — CDN
        WebACLId: !Ref WafWebAclArn
        Origins:
          - Id: s3-static-assets
            DomainName: !GetAtt StaticAssetsBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"

          - Id: alb-api
            DomainName: !Ref AlbDnsName
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              HTTPSPort: 443
              OriginReadTimeout: 30
              OriginKeepaliveTimeout: 5

        CacheBehaviors:
          # Static assets (JS, CSS, fonts) — long cache, served from S3 edge
          - PathPattern: "/static/*"
            TargetOriginId: s3-static-assets
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6   # CachingOptimized
            Compress: true

          # Product/media images — long cache, served from S3 edge
          - PathPattern: "/images/*"
            TargetOriginId: s3-static-assets
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6   # CachingOptimized
            Compress: true

        DefaultCacheBehavior:
          # API and dynamic content — no cache, forward to ALB
          TargetOriginId: alb-api
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad   # CachingDisabled
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3   # AllViewer
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - POST
            - PATCH
            - DELETE
          CachedMethods:
            - GET
            - HEAD

      Tags:
        - Key: ScalingPattern
          Value: horizontal

Outputs:
  DistributionId:
    Description: CloudFront distribution ID
    Value: !Ref AppDistribution

  DistributionDomainName:
    Description: CloudFront distribution domain name
    Value: !GetAtt AppDistribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-CDNDomainName"

  StaticAssetsBucketName:
    Description: S3 bucket for static assets
    Value: !Ref StaticAssetsBucket
