AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Horizontal Scaling Recipe — Observability Stack.
  CloudWatch alarms for horizontal scaling events: 5xx spikes, latency degradation,
  ASG near-max capacity, and Aurora ACU saturation.
  Ops team receives email for warnings; PagerDuty receives critical alerts.

Parameters:
  OpsTeamEmail:
    Type: String
    Description: Email address for ops team SNS notifications
  PagerDutyEndpoint:
    Type: String
    Description: PagerDuty HTTPS endpoint for critical alarms (SNS HTTPS subscription)
  AsgName:
    Type: String
    Description: Auto Scaling Group name (from horizontal-asg-config stack)
  AlbArn:
    Type: String
    Description: ALB ARN (used to derive ALB dimension for CloudWatch)
  TargetGroupArn:
    Type: String
    Description: Target group ARN (used to derive TG dimension for CloudWatch)
  DbClusterIdentifier:
    Type: String
    Default: horizontal-scaling-db
    Description: Aurora cluster identifier (from horizontal-aurora-serverless stack)

Resources:
  OpsTeamTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: horizontal-scaling-ops-alerts
      Subscription:
        - Protocol: email
          Endpoint: !Ref OpsTeamEmail

  CriticalAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: horizontal-scaling-critical-alerts
      Subscription:
        - Protocol: https
          Endpoint: !Ref PagerDutyEndpoint

  # 5xx spike — any server errors during peak are user-facing failures
  # Threshold: 10 errors in 1 minute. Adjust down for high-reliability workloads.
  FiveXxSpikeAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: horizontal-scaling-5xx-spike
      AlarmDescription: "5xx errors > 10 in 1 min — investigate ASG instance health and application logs"
      MetricName: HTTPCode_Target_5XX_Count
      Namespace: AWS/ApplicationELB
      Dimensions:
        - Name: LoadBalancer
          Value: !Select [1, !Split ["loadbalancer/", !Ref AlbArn]]
        - Name: TargetGroup
          Value: !Select [1, !Split ["targetgroup/", !Ref TargetGroupArn]]
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref CriticalAlertsTopic

  # Latency degradation — p95 response time > 500ms
  # Indicates instances are saturated or downstream services (DB, Redis) are slow.
  LatencyDegradationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: horizontal-scaling-latency-degradation
      AlarmDescription: "p95 latency > 500ms — check ASG CPU, Aurora ACU, and Redis CPU"
      MetricName: TargetResponseTime
      Namespace: AWS/ApplicationELB
      Dimensions:
        - Name: LoadBalancer
          Value: !Select [1, !Split ["loadbalancer/", !Ref AlbArn]]
        - Name: TargetGroup
          Value: !Select [1, !Split ["targetgroup/", !Ref TargetGroupArn]]
      ExtendedStatistic: p95
      Period: 120
      EvaluationPeriods: 1
      Threshold: 0.5
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref OpsTeamTopic

  # ASG near max capacity — approaching scaling ceiling
  # At 18 of 20 instances: raise MaxSize or investigate if load is expected.
  AsgNearMaxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: horizontal-scaling-asg-near-max
      AlarmDescription: "ASG at 18+ instances (max 20) — scaling headroom nearly exhausted, consider raising MaxSize"
      MetricName: GroupInServiceInstances
      Namespace: AWS/AutoScaling
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref AsgName
      Statistic: Maximum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 18
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref OpsTeamTopic

  # Aurora capacity high — approaching database scaling limit
  # At 56 of 64 ACU: notify DBA team. MaxCapacity can be raised to 128 ACU.
  AuroraCapacityHighAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: horizontal-scaling-aurora-capacity-high
      AlarmDescription: "Aurora capacity >= 56 ACU (max 64) — consider raising MaxCapacity or adding read replicas"
      MetricName: ServerlessDatabaseCapacity
      Namespace: AWS/RDS
      Dimensions:
        - Name: DBClusterIdentifier
          Value: !Ref DbClusterIdentifier
      Statistic: Maximum
      Period: 120
      EvaluationPeriods: 1
      Threshold: 56
      ComparisonOperator: GreaterThanOrEqualToThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref OpsTeamTopic

Outputs:
  OpsTeamTopicArn:
    Description: SNS topic for ops team alerts
    Value: !Ref OpsTeamTopic

  CriticalAlertsTopicArn:
    Description: SNS topic for critical alerts (PagerDuty)
    Value: !Ref CriticalAlertsTopic
