AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Horizontal Scaling Recipe - ElastiCache Redis.
  Primary + replica cluster for session store, application cache, rate limiting,
  and cart/state data.
  Redis is required for horizontal scaling: stateless instances must store
  all shared state externally. Without it, scale-out means data loss.

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for ElastiCache
  CacheSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Private subnets for ElastiCache (minimum 2 AZs)
  AppSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group of app instances (source for Redis access)

Resources:
  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Horizontal scaling recipe - Redis allow access from app instances
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref AppSecurityGroupId
      Tags:
        - Key: Name
          Value: horizontal-scaling-redis-sg
        - Key: ScalingPattern
          Value: horizontal

  RedisSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: horizontal-scaling-redis-subnets
      Description: Horizontal scaling recipe - Redis subnet group
      SubnetIds: !Ref CacheSubnetIds

  # Primary + 1 replica (NumCacheClusters: 2)
  # AutomaticFailoverEnabled: replica becomes primary if primary fails.
  # Typical TTLs (adapt to your use case):
  #   session data:    30 min
  #   application cache: 1–5 min
  #   rate-limit counters: 1 min window
  #   cart / user state: 1 hr
  # Eviction policy: allkeys-lru - when memory is full, evict least-recently-used keys.
  AppRedisCluster:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      ReplicationGroupId: horizontal-scaling-redis
      ReplicationGroupDescription: Horizontal scaling recipe - Redis cache cluster
      CacheNodeType: cache.r6g.large
      Engine: redis
      EngineVersion: "7.1"
      NumCacheClusters: 2   # Primary + replica
      AutomaticFailoverEnabled: true
      CacheSubnetGroupName: !Ref RedisSubnetGroup
      SecurityGroupIds:
        - !Ref RedisSecurityGroup
      AtRestEncryptionEnabled: true
      TransitEncryptionEnabled: true
      Tags:
        - Key: ScalingPattern
          Value: horizontal

Outputs:
  PrimaryEndpoint:
    Description: Redis primary endpoint (writes)
    Value: !GetAtt AppRedisCluster.PrimaryEndPoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-RedisPrimaryEndpoint"

  ReaderEndpoint:
    Description: Redis reader endpoint (reads)
    Value: !GetAtt AppRedisCluster.ReaderEndPoint.Address
    Export:
      Name: !Sub "${AWS::StackName}-RedisReaderEndpoint"

  RedisPort:
    Description: Redis port
    Value: !GetAtt AppRedisCluster.PrimaryEndPoint.Port
