AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Noblex / NEWSAN (2022) — SQS Async Processing Queues.
  Decouples HTTP critical path (payment + order write) from heavy processing.
  FIFO queue for order processing (exactly-once), Standard queues for
  inventory updates and notifications.

Resources:
  # Order processing DLQ — failed orders after 5 attempts
  OrderProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: noblex-order-dlq.fifo
      FifoQueue: true
      MessageRetentionPeriod: 1209600   # 14 days
      Tags:
        - Key: Project
          Value: noblex

  # Order processing: FIFO for exactly-once, ordered processing
  OrderProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: noblex-order-processing.fifo
      FifoQueue: true
      ContentBasedDeduplication: true
      VisibilityTimeout: 60
      ReceiveMessageWaitTimeSeconds: 20   # Long polling
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt OrderProcessingDLQ.Arn
        maxReceiveCount: 5
      Tags:
        - Key: Project
          Value: noblex

  # Inventory updates: Standard — eventual consistency acceptable, high throughput
  InventoryUpdatesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: noblex-inventory-updates
      VisibilityTimeout: 30
      Tags:
        - Key: Project
          Value: noblex

  # Email notifications: Standard — non-critical, fire-and-forget
  NotificationsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: noblex-notifications
      VisibilityTimeout: 30
      Tags:
        - Key: Project
          Value: noblex

Outputs:
  OrderProcessingQueueUrl:
    Description: Order processing FIFO queue URL
    Value: !Ref OrderProcessingQueue
    Export:
      Name: !Sub "${AWS::StackName}-OrderQueueUrl"

  OrderProcessingQueueArn:
    Description: Order processing FIFO queue ARN
    Value: !GetAtt OrderProcessingQueue.Arn

  InventoryUpdatesQueueUrl:
    Description: Inventory updates queue URL
    Value: !Ref InventoryUpdatesQueue
    Export:
      Name: !Sub "${AWS::StackName}-InventoryQueueUrl"

  NotificationsQueueUrl:
    Description: Notifications queue URL
    Value: !Ref NotificationsQueue
    Export:
      Name: !Sub "${AWS::StackName}-NotificationsQueueUrl"
